### ISSUE TITLE
Parameter console not working

### ISSUE THREAD

**Issue by eschizoid** [openhab/openhab-docker#11]
When executing `docker run -it openhab/openhab console`, this is the error that I'm getting:

```
+ set -euo pipefail
+ IFS='
	'
++ ls -A /openhab/userdata
+ '[' -z 'deploy
etc
logs
tmp' ']'
++ ls -A /openhab/conf
+ '[' -z 'html
items
persistence
rules
scripts
services
sitemaps
things
transform' ']'
+ '[' console = server ']'
+ '[' console = openhab ']'
+ '[' console = debug ']'
+ '[' console = console ']'
+ exec /openhab/runtime/karaf/bin/client
client: Ignoring predefined value for KARAF_HOME
Logging in as karaf
Failed to get the session.
```

**Comment by cyberkov** [comment]
Hello!

The console should be used in conjunction with an already running container. If you want to run an openhab container with a console right away you can start it in debug mode with the ``-it`` option.

Cheers
Hannes

**Comment by eschizoid** [comment]
@cyberkov Karaf was already running...

**Comment by cyberkov** [comment]
Hello @eschizoid !

You were mentioning that you used ``docker run`` which spawns a new container instance of the openhab image, which is not the same as using ``docker exec`` which runs the given command (as suggested in the documentation) in the context of the already spawned container. Whereas the first one is not supposed to work, I can confirm that the ``docker exec`` is not working as well, sorry for that.

I assumed that the entrypoint.sh is used when running exec as well. As a workaround you can use ```
docker exec -it openhab2 /openhab/runtime/karaf/bin/client``` until this issue is resolved.

Cheers
Hannes

**Comment by eschizoid** [comment]
Hey @cyberkov let me try what you are susggesting and i get back to you.

Mariano

**Comment by eschizoid** [comment]
Hey @cyberkov I was able to login to the Karaf console using the the following command:

`docker exec -it openhab2 /openhab/runtime/karaf/bin/client`

Unfortunately executing the client shell doesn't work.

**Comment by cniweb** [comment]
OK, can we change the line:
https://github.com/openhab/openhab-docker/blob/master/files/entrypoint.sh#L24
in `exec "${APPDIR}/runtime/karaf/bin/shell"`?

**Comment by cyberkov** [comment]
Hello @cniweb 
Unfortunately no because the entrypoint script is not used when using docker exec. We would need to create a script /usr/local/bin/console which contains the exec call, or even better, make a symlink to ${APPDIR}/runtime/karaf/bin/shell

At first I was thinking about expanding the $PATH variable with the folder, but I haven't found a proper way to do this.

**Comment by eschizoid** [comment]
Closing this since shell is working fine with Build 465

```
hab-docker $ docker exec -it aa51cbf7d3f6 /openhab/runtime/karaf/bin/shell
shell: Ignoring predefined value for KARAF_HOME

                          __  _____    ____
  ____  ____  ___  ____  / / / /   |  / __ )
 / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  |
/ /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /
\____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/
    /_/                        2.0.0-SNAPSHOT
                               Build #465

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.
```

**Comment by sjka** [comment]
@eschizoid please update the documentation accordingly!

**Comment by eschizoid** [comment]
Hi @sjka You mean the `README.md` file?

**Comment by sjka** [comment]
Yes, thanks for #32
