### ISSUE TITLE
charts (still) not working in openhab V2.2.0 ARM64 docker container (debian)

### ISSUE THREAD

**Issue by FoxRomeo** [openhab/openhab-docker#152]
Hi
the charts are not working in the container with Version 2.2.0 on ARM64 (debian) as the wrong fontconfig is installed. (In openhab/openhab:2.2.0-arm64-alpine it's working.)
"fontconfig" (without any parameters) is installed, therefor "fontconfig:arm64" is used.
But as the Java is running is 32bit the package "fontconfig:armhf" is required.
( see https://github.com/openhab/openhab-distro/issues/421 )

As simple workaround for (a running) openhab/openhab:2.2.0-arm64-debian:
_docker exec -ti <name_of_the_openhab2_container> bash
apt-get update ; apt-get install fontconfig:armhf -f -y ; apt-get clean -y ; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* ; exit_
Then stop and start the container. 

The only real solution is to correct the Dockerfile (change "fontconfig" to "fontconfig:armhf"). (#421 is closed but fix is still not implemented in new versions of the Dockerfile for ARM64)

**Comment by cniweb** [comment]
@FoxRomeo Thanks for your PR, see my comments!

**Comment by cniweb** [comment]
@FoxRomeo Build Error:
https://travis-ci.org/openhab/openhab-docker/jobs/335361237#L942

**Comment by wborn** [comment]
The Docker armhf image also seems to work without issues on arm64 systems. I tested this on a Raspberry Pi 3+ running in 64-bit mode (running [pi64 OS](https://github.com/bamarni/pi64)). That way the charts also work without any issue. Does that also work for you @FoxRomeo? 

If it does, I think we should create a proper arm64 image using a 64-bit Zulu JVM instead of the hybrid image (32-bit Zulu JVM) we currently have (causing all sorts of issues). So people can still use the armhf image on hardware constrained devices where performance matters (SBCs like the RPi etc.). WDYT @cniweb?

**Comment by cniweb** [comment]
I think a suitable arm64 image with a 64-bit Zulu JVM should be a good solution.
