### ISSUE TITLE
arm images have the wrong architecture set

### ISSUE THREAD

**Issue by bpteodor** [openhab/openhab-docker#184]
A docker inspect on the arm images (2.3.0-armhf-alpine, 2.3.0-armhf-debian) is revealing the wrong architecture (`"Architecture": "amd64",`). It should be something like `armv7l`.

This is causing problems when deploying in an orchestrated environment (like docker swarm), because the architecture is also used when deciding where to schedule.

**Comment by cniweb** [comment]
Hello @bpteodor we have arches:
https://github.com/openhab/openhab-docker/blob/master/update.sh#L6
and we use this multiarch images for debian:
https://hub.docker.com/r/multiarch/debian-debootstrap/tags/
https://github.com/openhab/openhab-docker/blob/master/update.sh#L66
and alpine:
https://hub.docker.com/r/library/alpine/
https://github.com/openhab/openhab-docker/blob/master/update.sh#L69
a `armv7l` is not present!

**Comment by wborn** [comment]
It seems the Architecture is inherited by the base images we use and there is no way to override it. 

These base images get the wrong Architecture because they are build with QEMU on a amd64 machine and they inherit it from `runtime.GOARCH` used by Docker on those machines.

See also https://github.com/moby/moby/issues/36552.

I added multi architecture manifests in https://github.com/openhab/openhab-docker/pull/213 so you no longer need to specify the architecture in the tag. Maybe you can use the new tags for solving the Docker Swarm orchestration issue?

**Comment by cniweb** [comment]
@bpteodor Can I close this Issue now?

**Comment by wborn** [comment]
There's also an issue for this in the issue tracker for the debian base image we use: 

https://github.com/multiarch/debian-debootstrap/issues/11
