### ISSUE TITLE
"KARAF_ETC is not valid" because userdata is not properly initialized from dist

### ISSUE THREAD

**Issue by hotzen** [openhab/openhab-docker#249]
hello, when starting the container, it fails with  `KARAF_ETC is not valid: /openhab/userdata/etc` because i mounted an "empty" userdata-volume that contains only an `.gitkeep` .

however as `ls -A` is used, this DOES list contents of the volume (said .gitkeep) and thus skips the copy-from-dist step in: https://github.com/openhab/openhab-docker/blob/dfa27163ad0193e02530b7c8ad751eddf5e9317b/2.4.0/alpine/entrypoint.sh#L48

is the `-A` really required?
or alternatively, could userdata-initialization be done a bit more specific by explicitly checking for the existence of e.g. `userdata/etc/version.properties` instead of doing this generic `initialize_volume` foobar?

thanks for the great work!

**Comment by hotzen** [comment]
i will now use the dist directly to initialize the userdata by myself:
https://github.com/openhab/openhab-docker/blob/master/2.4.0/alpine/Dockerfile-amd64#L14
    OPENHAB_URL="https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab%2F2.4.0%2Fopenhab-2.4.0.zip" \

**Comment by wborn** [comment]
> explicitly checking for the existence of e.g. userdata/etc/version.properties instead

But then someone will create an issue that all data in the volume was overwritten because for some unexplainable reason he/she removed this one file. :wink:

**Comment by hotzen** [comment]
what about the `ls -A`, is checking for hidden files required here?

or do you think my usage of `.gitkeep` to provide an "empty" userdata-volume is exotic?

**Comment by wborn** [comment]
The only reason the `entrypoint.sh` script initializes the volume is because the default files also need to be available to update existing data when updating an existing openHAB instance.

If the update mechanism wasn't there we'd put all that data into a normal Docker volume which would have exactly the same behavior as the script. I.e. if there is no dir or an empty dir the volume is initialized. If there is anything in the dir it isn't to prevent issues.

Usually you don't even need to commit the directories in Git using `.gitkeep` because Docker will automatically create them if they don't exist when initially starting the container. Though that behavior may very a bit between Docker builds/versions.

**Comment by wborn** [comment]
Let's close this since I still don't think it is a good idea to use an initialization mechanism different from how Docker normally initializes volumes.
