### ISSUE TITLE
Can bc be added to the image

### ISSUE THREAD

**Issue by sanderobdeijn** [openhab/openhab-docker#261]
I'm trying to read 1wire temp sensors in openhab. 
I'm using this guide https://dijit.us/?p=198
This guide uses a script that uses bc to calculate temperatures. Is it possible to add bc to the base image. Or should I add this to my own image?

**Comment by wborn** [comment]
It don't think many users need this so it would needlessly grow the image for them.

Each package that gets added potentially also makes the image less secure because it can have its own vulnerabilities.

Instead of creating and having to maintain your own image, you can also add a [script that installs it when the container is started](https://github.com/openhab/openhab-docker/blob/master/README.md#executing-shell-scripts-before-openhab-is-started).
