### ISSUE TITLE
adding ssh to container

### ISSUE THREAD

**Issue by Homer-Sim** [openhab/openhab-docker#268]
Hello,

I am not so familiar with Dockerfile to do it by my own. I need for executing commands on a remote RPi the ssh within the container. 
Each time updating I have to install it manually. Would it be an idea to add ssh from scratch?

Thanks

**Comment by wborn** [comment]
It seems to add 30 MB to the images which is quite a lot. If we'd add every requested package we'll end up with with Docker images having the size of a full blown OS. 

Each package that gets added potentially also makes the image less secure because it can have its own vulnerabilities.

Instead of creating and having to maintain your own image, you can also add a [script that installs it when the container is started](https://github.com/openhab/openhab-docker/blob/master/README.md#executing-shell-scripts-before-openhab-is-started).

**Comment by ldrrp** [comment]
I dont think its needed honestly, you can just ssh from the host machine perfectly fine with default password habopen.
