### ISSUE TITLE
Support adoptopenjdk

### ISSUE THREAD

**Issue by seaside1** [openhab/openhab-docker#393]
Adoptopenjdk seems to have fewer memory issues with GC compared to zulu and openjdk.
Could this be used when building docker images?

See https://github.com/openhab/openhab-core/issues/2142

**Comment by wborn** [comment]
Which specific memory issues do you run into with the Zulu JVM which are fixed by other JVMs?

**Comment by seaside1** [comment]
Not seen any specific issues, but have switched to adopt myself. I can see that my openhab instances are behaving much more nicely with adopt, and others seem to have the same experience.

https://community.openhab.org/t/syslog-errors-100-gb/116768/38

**Comment by wborn** [comment]
Are you sure that it is not just a placebo effect? :wink:

Most of the code used by all the OpenJDK based JVMs is the same so they all perform the same. I've seen presentations about that it doesn't really matter which one you pick. See [Performance of Microservices on Different JVMs](https://youtu.be/LPjxrXrlIp8).

I also did some benchmarking myself using the [Renaissence Suite](https://renaissance.dev/) and came to the same conclusions.

But I think there is a better reason to switch to Eclipse Temurin. That is because their code is more open source compared to Azul.

Also note that AdoptOpenJDK was [never](https://adoptopenjdk.net/quality.html#jck) a [TCK](https://en.wikipedia.org/wiki/Technology_Compatibility_Kit) certified JVM whereas the Temurin JVM is. You can even get [support for it from Azul](https://www.azul.com/blog/eclipse-temurin-new-distribution-of-openjdk/) if you want to. :wink:

**Comment by seaside1** [comment]
Installing openhabian gives you option to select jvm, would be nice to have that for docker as well, at least my opinion.
