### ISSUE TITLE
Changes in project structure

### ISSUE THREAD

**Issue by legacycode** [openhab/openhab-docker#53]
Hi,

as written in #26 i created a branch with a completly new file structure. I would like to discuss the changes in this thread To understand my changes i would like to share my personal experience with this repository:

I had a lot of problems developing with the Makefile. It is hard to read for beginners and there are a lot of arguments given to the Dockerfile.  The Dockerfiles where generated by the Makefile, build by travis and pushed to dockerhub. It was impossible for me to bring in individual content into the Dockerfiles for specific architectures.

I decided to take this approach, because it gives me a lot more flexibility to also add new images for libpcap support or maybe a fallback image for Orale Java on ARM32 devices as discussed in #26.

There are also other benifits i would like to share, if we use this approach:

Pros:
* Individual Dockerfiles for architectures
* Additional Dockerfiles for new features, e.g. libpcap support
* Dockerfiles are easy to read
* Dockerhub is linked to Github source
* Builds are automaticcally started
* You can view the Dockerfile content from Dockerhub for all architectures
* Travis builds the source without a dependency to Dockerhub

Cons:
* A little bit of redundance

**New file structure:
https://github.com/legacycode/openhab2-docker/tree/azul**

Dockerhub:
https://hub.docker.com/r/legacycode/openhab2-docker/tags/
Travis:
https://travis-ci.org/legacycode/openhab2-docker/builds/193485086

What do you think about my idea?

**Comment by cyberkov** [comment]
Hello!

Thank you for your hard work you are putting into refactoring. I am very grateful for that!
I had a look at the changes and i'd like to add some things, I as well encountered in the initial PR.

> Pros:
> Individual Dockerfiles for architectures

Thats not a pro imho because this is quite some duplication of code. Unfortunately it is not possible to use includes of any sort in Dockerfiles unless we would be using a shellscript in the buildphase of the container. This would clearly obfuscate the build process even more. The Makefile is basically just doing a `sed` operation on the top to switch to different architectures. Why not create a template for the basis and concatenate the arch-dependent parts into a final dockerfile?
> Additional Dockerfiles for new features, e.g. libpcap support

I like the idea of having all necessary libraries baked into the image, so I'd definitely would support adding libpcap into the baseimage. Have you tried using CAP_NET_RAW to allow libpcap run without root?
> Dockerfiles are easy to read

Well yes. So would be a template too :)

> Dockerhub is linked to Github source
> Builds are automaticcally started

nope and nope. They are linked to the github source of the "openhab-docker". You would need to have a change within this repo to have a build triggered (and therefore a push to dockerhub).
There are only two options to solve this:
- Integrate the Dockerfile into the mainrepo and have dockerhub or travis build "everything".
- Have Cloudbees Jenkins CI run a webhook on Travis to rebuild the "openhab-docker" repo (which leads to a push onto dockerhub with a recent version of openhab2)
> You can view the Dockerfile content from Dockerhub for all architectures

I wanted to have this as well, but you only get this feature when using dockers own automatic builds :( More importantly I think is, that the build process is open and can be seen by anyone who is interested. Never should there be any private source involved that is pushing towards dockerhub (which is the reason for all this multiarch-qemu madness ;) ).
> Travis builds the source without a dependency to Dockerhub

One more thing I'd like to bring up is versioning of containers. Homeassitant is tagging their release in the following format:
- dev
- latest (points to the latest stable release)
- 0.36.1
- 0.36
- and so on

I think it would make sense, now that we have an official release, to move to a similar structure on the dockerhub.

I hope this helps.
Cheers Hannes

**Comment by legacycode** [comment]
Good point. Thanks for that input. I created a new PR #56 and implemented an update.sh script. I found this solution on bigger docker hub repsitories and adapted it. The script is easy readable and maintainable.
