### ISSUE TITLE
Openhab 2.1.0 with upgrade option

### ISSUE THREAD

**Issue by dmartinpro** [openhab/openhab-docker#95]
Could be cool to have a fresh new openhab docker image with 2.1.0 stable and a clear procedure on how to upgrade a previously running version (using volume mounts).

**Comment by rkoshak** [comment]
In my experience, it only takes one or two days after the official release for the devs here to make a new version available on Dockerhub.

My upgrade approach (can't say whether it is right or wrong) is to stop the container, delete contents of userdata/cache and userdata/tmp, pull the new image and start the new container. The above is (was?) required to update all of the add-ons as well. Without it the old version of the add ons hang around.

when I have time I plan on working on a script that will connect to the karaf console and upgrade the installed addons (it isn't hard, just takes a smidgen of time I don't have).

**Comment by cniweb** [comment]
Docker Images are now up-to-date! #96 
The upgrade procedure is not integrated yet!

**Comment by wborn** [comment]
> The upgrade procedure is not integrated yet!

Upgrading an openHAB Docker container from 2.0.0 to 2.1.0 while keeping existing data still does not seem to work. Was the upgrade procedure in the end integrated @cniweb? There's also a whole "Updating the Image" section covering this issue in the [tutorial](https://community.openhab.org/t/running-openhab-2-in-docker/14267) by @rkoshak .

**Comment by rkoshak** [comment]
> There's also a whole "Updating the Image" section covering this issue in the tutorial by @rkoshak .

There have been a lot of changes to OH since that was written that makes the procedure written there no longer necessary, once there are some changes made to the entrypoint.sh script to copy over the files from ${APPDIR}/userdata.dist/etc that have a newer timestamp than those in the ${APPDIR}/userdata/etc but I've not implemented nor tested this yet let alone deemed it a reasonable approach.

userdata/cache and userdata/tmp also need to be cleared out and I don't know the best approach to do that yet (clear it out every time the container starts or detect a firstrun of the container and only clear it out then). 

Of course, the copying over of the select files in userdata/etc could also only happen on the first run as well.

But no matter how you look at it, entrypoint.sh is going to get more complicated.

**Comment by wborn** [comment]
Maybe all this data should not end up in the volumes in the first place? Then it gets removed when the container is pulled and no longer is an issue for newer versions of the container.

**Comment by rkoshak** [comment]
But there are lower level configurations that live there that some users need to edit. For example, userdata/etc/org.ops4j.pax.logging.cfg is where the logging config lives. keys.properties is where you set the ssh key so you don't need a password to log into karaf. Until userdata/etc moves somewhere else and we have a way to edit these configurations some other way that is not an option.
